### ISSUE TITLE
Can't build it on GCC 6.4.0

### ISSUE THREAD

**Issue by iterprise** [kjiwa/x86-boot-sector-c#2]
I got ld: section .sig LMA [0000000000007dfe,0000000000007dff] overlaps section .cseg LMA [0000000000007c00,0000000000007e62]

The code is too big.

**Comment by kjiwa** [comment]
This was a pet project from several years ago. I do not actively maintain it. You may submit a PR if you like.

**Comment by iterprise** [comment]
-fno-asynchronous-unwind-tables -fno-pic -fno-builtin -fno-ident  -fno-stack-protector
It can help.

**Comment by kjiwa** [comment]
I tried it with GCC 7.3.1 without those options and it builds fine without any changes.

```bash
$ gcc --version
gcc (GCC) 7.3.1 20180130 (Red Hat 7.3.1-2)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ make boot
cc -Wall -Os -m32 -c -o boot.o boot.c
ld  -T boot.ld -melf_i386 -o boot.elf boot.o
objcopy -O binary boot.elf boot
```
